
version: "3.9"

services:
  webapp:
    build: ./web_project
    volumes:
     - ./web_project:/django_app
    image: webapp:django_app
    container_name: django_web_app
    depends_on:
      - db
    ports: 
     - 8000:8000
    #command: gunicorn ITS.wsgi:application --bind 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000
  db:
    volumes:
      - ./data/db:/var/lib/postgresql/data
    image: postgres
    container_name: postgres_db
    environment:
      - POSTGRES_DB=its
      - POSTGRES_USER=equipo6
      - POSTGRES_PASSWORD=Equipo@6
  nginx:
    build: ./nginx
    volumes: 
     - ./web_project:/django_app
    image: nginx:nginx_app
    container_name: nginx_web_app
    depends_on:
      - webapp
    ports:
     - 80:80