
version: "3.9"

services:
  app:
    build: .
    volumes:
     - ./web_project:/django_app
    ports: 
     - 8000:8000
    image: app:django_app
    container_name: django_web_app
    command: python manage.py runserver 0.0.0.0:8000