# Generated by Django 4.1 on 2022-09-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCL', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
