# Generated by Django 4.1 on 2022-09-05 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usercontrol', '0003_alter_classroom_date_joined'),
        ('DCL', '0002_assignment_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcl_json_par1', models.JSONField()),
                ('dcl_json_par2', models.JSONField()),
                ('eq_x', models.JSONField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DCL.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercontrol.student')),
            ],
        ),
    ]
