# Generated by Django 4.1 on 2022-09-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCL', '0003_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='assignment/'),
        ),
    ]
