# Generated by Django 4.1 on 2022-09-08 21:10

import DCL.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCL', '0004_assignment_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=DCL.models.get_upload_path),
        ),
    ]
